general:
 cut_seq: GCGC
 genome: hg19
 pu1_motif: AGGAGT
 max_cpgs: 10

input:
 type: bed

sample_annotation:
 sampleID: sampleID
 bw_file: bw_file
 cov_file: cov_file
 cell_type: cell_type

rnbeads:
 sampleID: sampleID
 coverage: 10
 cell_type: cell_type
 assembly: mm10

dmcs:
 number: 500
 methylated: 0.95
 unmethylated: 0.05
 number_meth_unmeth: 100
 coverage_threshold: 10
 min_diff: 0.2

non_cut:
 n_amplicons: 75
 max_cpgs: 20
 length: 400
 n_cgis: 10
 n_promoters: 18
 n_genes: 24
 none: 23
 min_gc: 0.40
 max_gc: 0.50
